services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend

  backend:
    image: xaletch/diplome-backend-crm:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - APP_BASE_URL=${APP_BASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_ACCESS_CUSTOMER_SECRET=${JWT_ACCESS_CUSTOMER_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URI=${REDIS_URI}
      - REDIS_DB=${REDIS_DB}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - STORAGE_URL=${STORAGE_URL}
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    container_name: postgres-prod-container
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: redis-prod-container
    image: redis:8.2.2
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio-prod
    restart: unless-stopped
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    volumes:
      - minio-storage:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
  
  minio-init:
    image: minio/mc:latest
    networks:
      - backend
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
    entrypoint: ["/bin/sh", "-c"]
    command: >
      mc alias set minio http://minio:9000 $$MINIO_USER $$MINIO_PASSWORD &&
      mc mb --ignore-existing minio/location-avatars &&
      mc mb --ignore-existing minio/user-avatars &&
      mc mb --ignore-existing minio/company-avatars &&
      mc anonymous set public minio/location-avatars &&
      mc anonymous set public minio/user-avatars &&
      mc anonymous set public minio/company-avatars
    restart: on-failure

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio-storage:
