services:
  landing:
    container_name: landing
    image: xaletch/diploma-frontend-landing:latest
    platform: linux/amd64
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - shared

networks:
  shared:
    external: true
